### PR TITLE
automatically lint with `shellcheck`

### PR DESCRIPTION
**Pull request by Anton-Latukha**
Please, setup the CI - I recomment GitHub Actions for GitHub repo.
There you can statically check the script, like you can observe here: https://travis-ci.com/Anton-Latukha/img2djvu/jobs/245838710

For example block of code:
```bash
( #...
  if [ "$useocr" -gt 0 ] ; then
     printf "Starting OCR...\n"
     ocrodjvu --engine "$ocrengine" --language "$ocrlanguage" --jobs "$ocrjobs" --in-place --on-error=resume "$djvu"
  fi
) && rm -rf "$tmpdir" || (
  printf "Failure\nTemporary directory left: %s\n" "$tmpdir"
  exit 2
)
```

Used as if:
```
(A)
  && B
  || C
```

Was:
```
if A
  then B
  else C
```

But in `shell` that code is:
```
do C
if A
  then B
  else return exitcode of C
```

Actions `C` in shell here executed in parallel to `A`, and as so - executes and does things every time.

`shellcheck` is a very good code linter and most things it suggests is a good code practice. 
It has a knowledge DB wiki with examples and explanations.

It is also very useful to run it locally as: `shellcheck ./script`.

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
Ok, I think we waited enough and can close this.

**Comment by ashipunov** [comment]
Well, if you explain me what all this means, I might do something :)

AS

чт, 6 авг. 2020 г. в 22:56, Anton Latukha <notifications@github.com>:

**Comment by ashipunov** [comment]
Well, if you explain me what all this means, I might do something :)

AS

Ok, I think we waited enough and can close this.

**Comment by Anton-Latukha** [comment]
It was a drive-through PR, updated it so it is more readable. Since I submitted a Travis CI config - text followed with further actions.

You can run the `shellcheck ./img2djvu` locally to observe the script bugs and `shellcheck` would give good suggestions, you just need to follow what it found, and you would make a project more stable.

**Comment by ashipunov** [comment]
Thank you. I like the idea but it seems that I need the more detailed
instruction. How exactly I would use this on my local Linux machine? How to
install shellcheck, where is this config and how to use it?

AS

чт, 6 авг. 2020 г. в 23:48, Anton Latukha <notifications@github.com>:

**Comment by Anton-Latukha** [comment]
`shellcheck` is the most useful tool for `shell` development we know: https://github.com/koalaman/shellcheck
20k stars saying something.

It is readily available in most Linux repositories,

So if on Ubuntu:
```fish
sudo apt update
sudo apt install shellcheck
```

In project _README.md_ there is instructions for many OS systems: https://github.com/koalaman/shellcheck/blob/master/README.md#installing

---

Then when you have it installed - it provides `shellcheck` executable.

So to lint-check any shell scripts you like:
```fish
shellcheck /path/to/a/scriptFile.sh
```
And it would make "static analysis" of the code, it reads the code and gives direct suggestions from the own knowledge database. Every suggestion has ID, you can find detailed information on suggestion by googling: `shellckeck "name of the suggestion & ID"`, so all suggestions have solid ground and explained good.

**Comment by ashipunov** [comment]
Thanks for the explanation! I do not believe in stars :) but I will try to
install and use it. Thanks again!

AS

пт, 7 авг. 2020 г. в 15:51, Anton Latukha <notifications@github.com>:

**Pull request closed without merging**
